apiVersion: v1
kind: ConfigMap
metadata:
  name: fd-config
  namespace: fd-banking
data:
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "fd_bank_db"
  SPRING_PROFILES_ACTIVE: "prod"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  FD_EVENTS_TOPIC: "fd.lifecycle.v1"
  KAFKA_CONSUMER_GROUP: "fd-notification-service-v1"
  SMTP_HOST: "mailpit-service"
  SMTP_PORT: "1025"
