apiVersion: apps/v1
kind: Deployment
metadata:
  name: fd-service-deployment
  namespace: fd-banking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fd-service
  template:
    metadata:
      labels:
        app: fd-service
    spec:
      containers:
        - name: fd-service
          image: fd-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 45
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://$(DB_HOST):$(DB_PORT)/$(DB_NAME)?useSSL=false&serverTimezone=UTC"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: fd-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: fd-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: fd-config
                  key: DB_NAME
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fd-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fd-secret
                  key: JWT_SECRET
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: fd-config
                  key: SPRING_PROFILES_ACTIVE
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: fd-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: FD_EVENTS_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: fd-config
                  key: FD_EVENTS_TOPIC
            - name: FD_KAFKA_ENABLED
              value: "true"
